TARGET			:= test_sort
CSRCS			:= $(TARGET).c

CSRCS			+= bubblsrt.c
CSRCS			+= heapsort.c
CSRCS			+= instnsrt.c
CSRCS			+= mergesrt.c
CSRCS			+= quicksrt.c
CSRCS			+= radixsrt.c
CSRCS			+= slctnsrt.c
CSRCS			+= shellsrt.c

include ../../prj_native.mk
